language: node_js
node_js:
- '8'
install:
- yarn
- yarn lint
- yarn build
cache:
  yarn: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: david.ahern26@gmail.com
  password:
    secure: FVZyJ3sR4vMrkHBbfYxY6swR3i4IY3q1l/aUR4GNCj5IWCxo97HxDyfZ/PDwq8HsH4lZRXMZNglVNPhABoETjlMDdm03194lDtjKIL2irh4eGDWKFTcxCC+tw4vEsFfXroBDXxnx03tHxkWQhEtR64AtXHAeZCkd6oWZpiwUu0MYezgXbngl0V06rP9ZxDVIhBi21ZZqV4bSDFNPAOsIgFbDbfFZdIWV0OZMqp0OgeHDEZoIMi5EUXFOV5nit/E4Cv8pfSc7hwcDygTHdu/rcgC0cS5XSv7lL7+vxHXjh9mNRXeD3DlXKUI/+7tWEasVw+DA0Ulq5tHDOxuZWzBGM+Gw0bjOZwIdkN4CaRUu/UB0Hv4FUktz/f8vBKyn4/aEiqWLeakBBg59nOqfvSNdYeHb456K18QlXj0H3HdeXN7AprJp/V66w60QZDNBWL1kK/cxmmW2sdbqzpTyII6qDQpHABCbR98y7/NF+wu7aM4tit3G3uxPd2bLOeiW+pF8tI+8BRpIlAqbs3YWf0KgYtNExIwsjS01x95ifGTK4X3ODcOMZrXpmGZatkCnrMFojZzp5LCYnRL76OEfzTbAM9GcWj97U5+uYFCmVNK35IuhlTWPzEWmFAgqJp+VzFWja6sd1zq3NyICipmvc3J0bepfwpBm8oX6GWk70rKvVOo=
  organization: thor
  space: prod
  on:
    repo: redux-mesh/redux-mesh-ui
    branch: master
