language: node_js
node_js:
- '8'
install:
- yarn
- yarn lint
- yarn build
cache:
  yarn: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: david.ahern26@gmail.com
  password:
    secure: Vvs7T6VOdIsg4visVZZEskJgE3TJ/6PC3IHmTI8T1/g68xKWbqJuZI6TGVt/XvHaSTsoSr5WeQLqxMcEUdzt9uhjKPNDqKZz9tCDRDp3CMSzdTABmXNT4oyD8DzWpbtgeolxIQ+i8NjQ3fuF/zbgC5SdtLLvxJStM/QFVgZ/TpRMMoOnZLss2BDibHfQcj71jwRyJKR0AcyfNpdBSR44iEZ3WwXx6G8H9+cwbZi3XIwmx/HJA+7PMrbxmCzpEdnnPACl3WgTIGszqs+VzqPYEVpqygtSBlJkAcvIhV7N/XGl7cM/zN+7m6NsWOge0Gq6B2WZwBfsPmTFZpu2oSaToJBvlOwsLPzx66tnhxpiZl5CE+1vnPZ9AXLemWMI+0HiDkNLLtLpaVaSSiVJPGE1m7KgpOkn8jVoiZ9FJ/20Pk7HpiD3oM5s1iTc84JHtljny9z2sSuXAO97nYcGAZ5OouZ85RY8o5JpWjLL8FhMCPR4N3tpxDjRiTwfgqhgeqLk3BBWdOr968fLk4tToPXrxpGQN6gBp1RvO5+JNO9bJwlC0foACMGdP9VHZyu1J6Op9hCAlULNcuXV5VYmMmHWvRR+VBcJ03Y2Q9Szx5dIsrVaGhxvB301RV5K7RVYT8woDmpdJvGJ2WM+1hTPWGyKkFKZ1evL+pz/ivIvL15x3e4=
  organization: thor
  space: prod
  on:
    repo: el-davo/retro-ui
    branch: master
