language: node_js
node_js:
- '8'
install:
- yarn
- yarn lint
- yarn build
cache:
  yarn: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: david.ahern26@gmail.com
  password:
    secure: mynqt85iHgHaZOYyyx9dQzgZmGxMZYaK/2iJdKTn66TUlRwfTz/JjfJLh8CoE4ucwa36ChBdyLsb6niH35IdpsP6X41jPpQ2KJI3oD09Z+RhM/L+L3BTAzqF03f7DqqYU+YWJxGbBhF4cgKiU5Me3Gg2PBFRBeaa7E+RNyizbXA65MvCM62zwozpwQtGn2JaW56gC+4s3xebqPDrTyeqztwTi21kagKuP6fbWyZSlt7IjTHGYs3YW1dD6vSeFsxyYpMllKYWxqZRs/3AUga2vLPNNDW98T2gCH5RDTbNx85z02lzm02duUCW44PjbZDVD/nLfDNWyDuiwkQXngPPJhHkMtVfwGWJvVV3wmFuAh4JY8FNIxqmN7AteadjR2PnkM8ZuxGuQwcjsbvCPC7ZR6XU5ZHVShpCXpi097RlIYjbKsF/naKOkGa1JkbzoJvWb2PDG0oZkoH8beDviJ1Z/wBnauNlSMNOrP/klsI7+HvCWUOtUcgnuyR2RK6NoBQXO8PNXRre8EdXGN4NBLt5EB7EcB/S9IOWXyjllhCexgk+LzBwoAHhxxGC0WpJKBuge2F75QWpfMLUsY59mBrogn4Lij1qBGmcn1eTxFxC6DnLoeWrdXi3aOQITHmDcQTMi604FoKJyVQgr8uK/3C1ga6wSrEWJ5T6Ss8jsdMIDC0=
  organization: thor
  space: prod
  on:
    repo: codetemplator/codetemplator-ui
    branch: master
