version: '3'

services:

  mongodb:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - 8001:27017
    command: mongod --smallfiles --logpath=/dev/null

  redux-mesh-api:
    image: reduxmesh/api:latest
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      main:
        aliases:
          - redux-mesh-api
    command: >
      /bin/bash -c "sleep 2; node ."

networks:
  main:

volumes:
  mongodb:
  yarn:
  mongodata:
