version: '2'

services:

  db:
    image: mysql
    container_name: database.dev
    command: mysqld --user=root --verbose
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "retro"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8001:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_USERNAME: username
      MYSQL_ROOT_PASSWORD: password

  retro-api:
      image: eahedav/retro-api:latest
      depends_on:
        - db
      ports:
        - 3000:3000
      command: >
        /bin/bash -c "sleep 2; node ."

volumes:
  db:
  yarn:
