version: '3'

services:

  codetemplator-api:
    image: codetemplator/api:latest
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=dev
    networks:
      main:
        aliases:
          - codetemplator-api
    command: >
      /bin/bash -c "sleep 5; node ."

networks:
  main:

volumes:
  mongodb:
  yarn:
